version: '3.8'

services:
  toyota-rag-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Optional: Mount data directories if you want to persist data
      - ./data:/app/data
      - ./docs:/app/docs
      - ./chroma_db:/app/chroma_db
    environment:
      - CHAINLIT_HOST=0.0.0.0
      - CHAINLIT_PORT=8000
